import React from 'react';
import { AlertTriangle, Info, ShieldCheck } from 'lucide-react';

interface TrustBannerProps {
  customMessage?: string;
  type?: 'general' | 'ai' | 'compensation' | 'synthetic';
  className?: string;
}

export const TrustBanner: React.FC<TrustBannerProps> = ({
  customMessage,
  type = 'synthetic',
  className = '',
}) => {
  if (type === 'compensation') {
    return (
      <div className={`flex items-start gap-2.5 p-3 rounded-lg bg-amber-50 border border-amber-200 text-amber-900 text-xs ${className}`}>
        <AlertTriangle className="w-4 h-4 text-amber-700 shrink-0 mt-0.5" />
        <div>
          <span className="font-semibold">Illustrative Estimate — Not an Official Determination: </span>
          {customMessage || 'Simulated calculations are based on configured prototype formulas and synthetic baseline rates under RFCTLARR Act 2013. Official compensation is determined solely by the Competent Authority Land Acquisition (CALA) upon formal award.'}
        </div>
      </div>
    );
  }

  if (type === 'ai') {
    return (
      <div className={`flex items-start gap-2.5 p-3 rounded-lg bg-blue-50 border border-blue-200 text-blue-900 text-xs ${className}`}>
        <Info className="w-4 h-4 text-blue-700 shrink-0 mt-0.5" />
        <div>
          <span className="font-semibold">AI-Generated Summary — Verify Against Source Document: </span>
          {customMessage || 'Responses and extracted insights are generated by language model interpretation of draft SIA records. Always cross-reference against official gazette notifications and published project reports.'}
        </div>
      </div>
    );
  }

  return (
    <div className={`flex items-center justify-between gap-3 px-4 py-2 bg-slate-900 text-slate-300 text-xs border-b border-slate-800 ${className}`}>
      <div className="flex items-center gap-2">
        <ShieldCheck className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
        <span>
          <strong className="text-white font-medium">Smart India Hackathon 2026 Prototype: </strong>
          Synthetic Demonstration Data — not official government data. Designed for research and policy evaluation.
        </span>
      </div>
      <div className="hidden sm:flex items-center gap-3 text-slate-400 text-[11px]">
        <span>Standard: RFCTLARR Act 2013</span>
        <span>·</span>
        <span>Data Protocol: NDAP v2.1</span>
      </div>
    </div>
  );
};
